In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv('./data/spam.csv', encoding='latin-1')
df = pd.DataFrame(data)
df.head()

In [ ]:
df = data[['v1', 'v2']]
df.columns = ['label', 'email']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['email'])
y = df['label'].apply(lambda x: 1 if x == 'spam' else 0)

__X is look like this:__
```
[[0 0 0 1 0 1 1 1 0 0 1 0 0 0 0]
 [0 1 0 0 1 1 0 0 1 0 0 1 1 0 0]
 [1 0 1 0 1 0 0 0 1 1 0 0 0 1 1]]
```
__y is look like:__
```
0       0
1       0
2       1
```
`[0 0 0 1 0 1 1 1 0 0 1 0 0 0 0]` pattern represent `0` means `not span` and 


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.naive_bayes import MultinomialNB

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

classifier = MultinomialNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# User Input

In [ ]:
 user_input = input()

In [ ]:
input_features = vectorizer.transform([user_input])
prediction = classifier.predict(input_features)

In [ ]:
print("Spam" if prediction == 1 else "Not Spam")