In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv('./data/spam.csv', encoding='latin-1')
df = pd.DataFrame(data)
df.head()

In [ ]:
df = data[['v1', 'v2']]
df.columns = ['label', 'email']

In [97]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['email'])
y = df['label'].apply(lambda x: 1 if x == 'spam' else 0)

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: label, Length: 5572, dtype: int64


__X is look like this:__
```
[[0 0 0 1 0 1 1 1 0 0 1 0 0 0 0]
 [0 1 0 0 1 1 0 0 1 0 0 1 1 0 0]
 [1 0 1 0 1 0 0 0 1 1 0 0 0 1 1]]
```
__y is look like:__
```
0       0
1       0
2       1
```
`[0 0 0 1 0 1 1 1 0 0 1 0 0 0 0]` pattern represent `0` means `not span` and 


In [87]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score
from sklearn.naive_bayes import MultinomialNB

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

classifier = MultinomialNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9784688995215312
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      1453
           1       0.92      0.92      0.92       219

    accuracy                           0.98      1672
   macro avg       0.95      0.95      0.95      1672
weighted avg       0.98      0.98      0.98      1672

Confusion Matrix:
 [[1435   18]
 [  18  201]]


# User Input

In [ ]:
 user_input = input()

In [ ]:
input_features = vectorizer.transform([user_input])
prediction = classifier.predict(input_features)

In [ ]:
print("Spam" if prediction == 1 else "Not Spam")